# Tax profiles for global residency support
TAX_PROFILES = {
    'GB': {
        'name': 'United Kingdom',
        'flag': '🇬🇧',
        'currency': 'GBP',
        'symbol': '£',
        'cgt_annual_exempt': 3000,
        'cgt_rate_basic': 0.18,
        'cgt_rate_higher': 0.24,
        'income_tax_free': 12570,
        'income_bands': [
            {'limit': 50270, 'rate': 0.20, 'label': 'Basic rate'},
            {'limit': 125140, 'rate': 0.40, 'label': 'Higher rate'},
            {'limit': None,   'rate': 0.45, 'label': 'Additional rate'},
        ],
        'pension_label': 'Pension',
        'pension_tax_note': 'Tax-free growth, income tax on withdrawal',
        'isa_label': 'ISA',
        'isa_annual_limit': 20000,
        'isa_note': 'Tax-free, no CGT',
        'pension_annual_limit': 60000,
        'has_cgt_exempt': True,
        'notes': 'CGT exempt amount £3,000 (2024/25). ISA allowance £20,000/yr.',
    },
    'US': {
        'name': 'United States',
        'flag': '🇺🇸',
        'currency': 'USD',
        'symbol': '$',
        'cgt_annual_exempt': 0,
        'cgt_rate_basic': 0.15,   # Long-term for middle income
        'cgt_rate_higher': 0.20,  # Long-term high income
        'income_tax_free': 14600, # Standard deduction (single, 2024)
        'income_bands': [
            {'limit': 47150,  'rate': 0.12, 'label': '12% bracket'},
            {'limit': 100525, 'rate': 0.22, 'label': '22% bracket'},
            {'limit': 191950, 'rate': 0.24, 'label': '24% bracket'},
            {'limit': 243725, 'rate': 0.32, 'label': '32% bracket'},
            {'limit': 609350, 'rate': 0.35, 'label': '35% bracket'},
            {'limit': None,   'rate': 0.37, 'label': '37% bracket'},
        ],
        'pension_label': '401(k) / IRA',
        'pension_tax_note': 'Traditional: tax-deferred. Roth: tax-free withdrawal.',
        'isa_label': 'Roth IRA',
        'isa_annual_limit': 7000,
        'isa_note': 'Tax-free growth (post-tax contributions)',
        'pension_annual_limit': 23000,
        'has_cgt_exempt': False,
        'notes': 'Long-term CGT: 0%, 15%, or 20% depending on income. No standard exempt amount.',
    },
    'IN': {
        'name': 'India',
        'flag': '🇮🇳',
        'currency': 'INR',
        'symbol': '₹',
        'cgt_annual_exempt': 125000,  # ₹1.25 lakh for LTCG equities
        'cgt_rate_basic': 0.125,      # 12.5% LTCG on equities
        'cgt_rate_higher': 0.20,      # 20% for other assets (with indexation removed 2024)
        'income_tax_free': 300000,    # New regime basic exemption
        'income_bands': [
            {'limit': 700000,  'rate': 0.05,  'label': '5%'},
            {'limit': 1000000, 'rate': 0.10,  'label': '10%'},
            {'limit': 1200000, 'rate': 0.15,  'label': '15%'},
            {'limit': 1500000, 'rate': 0.20,  'label': '20%'},
            {'limit': None,    'rate': 0.30,  'label': '30%'},
        ],
        'pension_label': 'NPS / PPF / EPF',
        'pension_tax_note': 'NPS: EEE status. PPF: EEE status. EPF: EEE up to limits.',
        'isa_label': 'PPF / ELSS',
        'isa_annual_limit': 150000,
        'isa_note': 'PPF ₹1.5L/yr, ELSS 80C deduction',
        'pension_annual_limit': 200000,
        'has_cgt_exempt': True,
        'notes': 'LTCG >1 year equities: 12.5% above ₹1.25L. STCG: 20%. Budget 2024 changes apply.',
    },
    'AE': {
        'name': 'UAE',
        'flag': '🇦🇪',
        'currency': 'AED',
        'symbol': 'د.إ',
        'cgt_annual_exempt': 0,
        'cgt_rate_basic': 0.0,
        'cgt_rate_higher': 0.0,
        'income_tax_free': 999999999,
        'income_bands': [],
        'pension_label': 'DEWS / Gratuity',
        'pension_tax_note': 'No personal income tax. Gratuity on employment end.',
        'isa_label': 'Savings',
        'isa_annual_limit': 0,
        'isa_note': 'No tax wrapper needed — no personal income tax',
        'pension_annual_limit': 0,
        'has_cgt_exempt': False,
        'notes': 'Zero personal income tax, zero CGT. Corporate tax 9% on profits >AED 375k.',
    },
    'SG': {
        'name': 'Singapore',
        'flag': '🇸🇬',
        'currency': 'SGD',
        'symbol': 'S$',
        'cgt_annual_exempt': 0,
        'cgt_rate_basic': 0.0,
        'cgt_rate_higher': 0.0,
        'income_tax_free': 20000,
        'income_bands': [
            {'limit': 30000,  'rate': 0.02,  'label': '2%'},
            {'limit': 40000,  'rate': 0.035, 'label': '3.5%'},
            {'limit': 80000,  'rate': 0.07,  'label': '7%'},
            {'limit': 120000, 'rate': 0.115, 'label': '11.5%'},
            {'limit': 160000, 'rate': 0.15,  'label': '15%'},
            {'limit': 200000, 'rate': 0.18,  'label': '18%'},
            {'limit': 240000, 'rate': 0.19,  'label': '19%'},
            {'limit': 280000, 'rate': 0.195, 'label': '19.5%'},
            {'limit': 320000, 'rate': 0.20,  'label': '20%'},
            {'limit': None,   'rate': 0.22,  'label': '22%'},
        ],
        'pension_label': 'CPF',
        'pension_tax_note': 'CPF contributions tax-deductible. Withdrawals tax-free at 55.',
        'isa_label': 'SRS',
        'isa_annual_limit': 15300,
        'isa_note': 'SRS S$15,300/yr, tax-deductible',
        'pension_annual_limit': 37740,
        'has_cgt_exempt': False,
        'notes': 'No CGT. Income tax progressive 0–22%. CPF mandatory savings scheme.',
    },
    'CA': {
        'name': 'Canada',
        'flag': '🇨🇦',
        'currency': 'CAD',
        'symbol': 'CA$',
        'cgt_annual_exempt': 0,
        'cgt_rate_basic': 0.165,   # Federal 33% on 50% inclusion = ~16.5% effective
        'cgt_rate_higher': 0.267,  # Post June 2024 budget 2/3 inclusion for gains >$250k
        'income_tax_free': 15705,
        'income_bands': [
            {'limit': 57375,  'rate': 0.205, 'label': '20.5%'},
            {'limit': 114750, 'rate': 0.26,  'label': '26%'},
            {'limit': 158519, 'rate': 0.29,  'label': '29%'},
            {'limit': None,   'rate': 0.33,  'label': '33%'},
        ],
        'pension_label': 'RRSP',
        'pension_tax_note': 'Tax-deductible contributions. Taxed on withdrawal.',
        'isa_label': 'TFSA',
        'isa_annual_limit': 7000,
        'isa_note': 'TFSA CA$7,000/yr, fully tax-free',
        'pension_annual_limit': 31560,
        'has_cgt_exempt': False,
        'notes': '50% capital gains inclusion (or 2/3 above $250k after June 2024). Provincial tax additional.',
    },
    'AU': {
        'name': 'Australia',
        'flag': '🇦🇺',
        'currency': 'AUD',
        'symbol': 'A$',
        'cgt_annual_exempt': 0,
        'cgt_rate_basic': 0.175,   # 50% discount on marginal rate ~35%
        'cgt_rate_higher': 0.225,  # Top marginal 45% with 50% discount
        'income_tax_free': 18200,
        'income_bands': [
            {'limit': 45000,  'rate': 0.19, 'label': '19%'},
            {'limit': 135000, 'rate': 0.325,'label': '32.5%'},
            {'limit': 190000, 'rate': 0.37, 'label': '37%'},
            {'limit': None,   'rate': 0.45, 'label': '45%'},
        ],
        'pension_label': 'Superannuation',
        'pension_tax_note': '15% tax in accumulation, tax-free after 60.',
        'isa_label': 'Super',
        'isa_annual_limit': 27500,
        'isa_note': 'Concessional contributions A$27,500/yr',
        'pension_annual_limit': 27500,
        'has_cgt_exempt': False,
        'notes': '50% CGT discount for assets held >12 months. Medicare levy 2% additional.',
    },
    'DE': {
        'name': 'Germany',
        'flag': '🇩🇪',
        'currency': 'EUR',
        'symbol': '€',
        'cgt_annual_exempt': 1000,
        'cgt_rate_basic': 0.25,
        'cgt_rate_higher': 0.25,   # Flat Abgeltungsteuer
        'income_tax_free': 11604,
        'income_bands': [
            {'limit': 17006,  'rate': 0.14, 'label': '14%'},
            {'limit': 66761,  'rate': 0.24, 'label': 'up to 42%'},
            {'limit': 277826, 'rate': 0.42, 'label': '42%'},
            {'limit': None,   'rate': 0.45, 'label': '45%'},
        ],
        'pension_label': 'Riester / bAV',
        'pension_tax_note': 'State-subsidised Riester pension. Company bAV tax-deferred.',
        'isa_label': 'Freistellungsauftrag',
        'isa_annual_limit': 1000,
        'isa_note': '€1,000 annual savings allowance (Sparerpauschbetrag)',
        'pension_annual_limit': 7248,
        'has_cgt_exempt': True,
        'notes': 'Flat 25% Abgeltungsteuer + 5.5% solidarity surcharge + church tax where applicable.',
    },
    'FR': {
        'name': 'France',
        'flag': '🇫🇷',
        'currency': 'EUR',
        'symbol': '€',
        'cgt_annual_exempt': 0,
        'cgt_rate_basic': 0.30,    # Flat PFU / prélèvement forfaitaire unique
        'cgt_rate_higher': 0.30,
        'income_tax_free': 11294,
        'income_bands': [
            {'limit': 28797,  'rate': 0.11, 'label': '11%'},
            {'limit': 82341,  'rate': 0.30, 'label': '30%'},
            {'limit': 177106, 'rate': 0.41, 'label': '41%'},
            {'limit': None,   'rate': 0.45, 'label': '45%'},
        ],
        'pension_label': 'PER / Retraite',
        'pension_tax_note': 'PER contributions deductible. Taxed on withdrawal.',
        'isa_label': 'PEA / Livret A',
        'isa_annual_limit': 150000,
        'isa_note': 'PEA €150k limit, tax-free after 5 years',
        'pension_annual_limit': 32909,
        'has_cgt_exempt': False,
        'notes': 'Flat 30% PFU (12.8% IR + 17.2% social charges). PEA tax-free after 5 years.',
    },
}

CURRENCIES = {
    'GBP': {'name': 'British Pound',        'symbol': '£',    'flag': '🇬🇧'},
    'USD': {'name': 'US Dollar',            'symbol': '$',    'flag': '🇺🇸'},
    'EUR': {'name': 'Euro',                 'symbol': '€',    'flag': '🇪🇺'},
    'INR': {'name': 'Indian Rupee',         'symbol': '₹',    'flag': '🇮🇳'},
    'AED': {'name': 'UAE Dirham',           'symbol': 'د.إ',  'flag': '🇦🇪'},
    'SGD': {'name': 'Singapore Dollar',     'symbol': 'S$',   'flag': '🇸🇬'},
    'CAD': {'name': 'Canadian Dollar',      'symbol': 'CA$',  'flag': '🇨🇦'},
    'AUD': {'name': 'Australian Dollar',    'symbol': 'A$',   'flag': '🇦🇺'},
    'CHF': {'name': 'Swiss Franc',          'symbol': 'Fr',   'flag': '🇨🇭'},
    'JPY': {'name': 'Japanese Yen',         'symbol': '¥',    'flag': '🇯🇵'},
    'HKD': {'name': 'Hong Kong Dollar',     'symbol': 'HK$',  'flag': '🇭🇰'},
    'NZD': {'name': 'New Zealand Dollar',   'symbol': 'NZ$',  'flag': '🇳🇿'},
    'MYR': {'name': 'Malaysian Ringgit',    'symbol': 'RM',   'flag': '🇲🇾'},
    'SAR': {'name': 'Saudi Riyal',          'symbol': '﷼',    'flag': '🇸🇦'},
    'QAR': {'name': 'Qatari Riyal',         'symbol': 'QR',   'flag': '🇶🇦'},
}
